Added web services changes
RedHatInsights/app-common-js pull request #6
Opened 2021-01-22 17:11 UTC by psav

2021-01-22 17:12 UTC, psav commented
To be merged after - https://github.com/RedHatInsights/clowder/pull/185

2021-01-27 17:45 UTC, kylape commented
`internal` is still referenced in this PR

2021-01-27 17:56 UTC, kylape requested changes
`internal` is still referenced in this PR

2021-01-27 18:02 UTC, kylape requested changes
So do you now generate the code based on the schema?

2021-01-27 18:02 UTC, kylape commented on index.js
> +            for(i = 0; i < Config.data.privateEndpoints.length; i++){
would `Array.prototype.forEach()` work here?

2021-01-28 09:39 UTC, merged